version: '3'

services:

  reverse-proxy:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  app:
    container_name: app
    build: ./
    environment:
      - FLASK_APP=app.py
    command: flask run --host=0.0.0.0 --port=8080
    ports:
      - "8090:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin.rule=Host(`localhost`)"
      - "traefik.http.routers.pgadmin.entrypoints=web"