version: '3'

services:
  app:
    image: ctf-elixirs
    container_name: app
    build: ./
    environment:
      - FLASK_APP=app.py
    command: flask run --host=0.0.0.0 --port=8080
    expose:
      - 8080
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.elixirs.rule=PathPrefix(`/elixirs`)"
      - "traefik.http.routers.elixirs.entrypoints=http"
      - "traefik.http.services.elixirs.port=8080"
      - "traefik.http.middlewares.elixirs.stripprefix.prefixes=/elixirs"